-- MySQL Script generated by MySQL Workbench
-- Sat Apr  4 19:27:37 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema heroes_dragons
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema heroes_dragons
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `heroes_dragons` DEFAULT CHARACTER SET utf8 ;
USE `heroes_dragons` ;

-- -----------------------------------------------------
-- Table `heroes_dragons`.`characters_sheets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroes_dragons`.`characters_sheets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `character_name` VARCHAR(255) NULL,
  `content` LONGTEXT NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Contenu des differents manuels d\'utilisation.';


-- -----------------------------------------------------
-- Table `heroes_dragons`.`character_sheet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroes_dragons`.`character_sheet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  `characters_sheets_id` INT NOT NULL,
  PRIMARY KEY (`id`, `characters_sheets_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroes_dragons`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroes_dragons`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `isAdminUser` TINYINT NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroes_dragons`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroes_dragons`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroes_dragons`.`users_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroes_dragons`.`users_roles` (
  `users_id` INT NOT NULL,
  `roles_id` INT NOT NULL,
  PRIMARY KEY (`users_id`, `roles_id`),
  CONSTRAINT `fk_users_has_roles_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `heroes_dragons`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_roles_roles1`
    FOREIGN KEY (`roles_id`)
    REFERENCES `heroes_dragons`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_users_has_roles_roles1_idx` ON `heroes_dragons`.`users_roles` (`roles_id` ASC);

CREATE INDEX `fk_users_has_roles_users1_idx` ON `heroes_dragons`.`users_roles` (`users_id` ASC);


-- -----------------------------------------------------
-- Table `heroes_dragons`.`character_sheet_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroes_dragons`.`character_sheet_users` (
  `character_sheet_id` INT NOT NULL,
  `character_sheet_characters_sheets_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`character_sheet_id`, `character_sheet_characters_sheets_id`, `users_id`),
  CONSTRAINT `fk_character_sheet_has_users_character_sheet1`
    FOREIGN KEY (`character_sheet_id` , `character_sheet_characters_sheets_id`)
    REFERENCES `heroes_dragons`.`character_sheet` (`id` , `characters_sheets_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_character_sheet_has_users_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `heroes_dragons`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_character_sheet_has_users_users1_idx` ON `heroes_dragons`.`character_sheet_users` (`users_id` ASC);

CREATE INDEX `fk_character_sheet_has_users_character_sheet1_idx` ON `heroes_dragons`.`character_sheet_users` (`character_sheet_id` ASC, `character_sheet_characters_sheets_id` ASC);


-- -----------------------------------------------------
-- Table `heroes_dragons`.`character_sheet_characters_sheets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroes_dragons`.`character_sheet_characters_sheets` (
  `character_sheet_id` INT NOT NULL,
  `character_sheet_characters_sheets_id` INT NOT NULL,
  `characters_sheets_id` INT NOT NULL,
  PRIMARY KEY (`character_sheet_id`, `character_sheet_characters_sheets_id`, `characters_sheets_id`),
  CONSTRAINT `fk_character_sheet_has_characters_sheets_character_sheet1`
    FOREIGN KEY (`character_sheet_id` , `character_sheet_characters_sheets_id`)
    REFERENCES `heroes_dragons`.`character_sheet` (`id` , `characters_sheets_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_character_sheet_has_characters_sheets_characters_sheets1`
    FOREIGN KEY (`characters_sheets_id`)
    REFERENCES `heroes_dragons`.`characters_sheets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_character_sheet_has_characters_sheets_characters_sheets1_idx` ON `heroes_dragons`.`character_sheet_characters_sheets` (`characters_sheets_id` ASC);

CREATE INDEX `fk_character_sheet_has_characters_sheets_character_sheet1_idx` ON `heroes_dragons`.`character_sheet_characters_sheets` (`character_sheet_id` ASC, `character_sheet_characters_sheets_id` ASC);


-- -----------------------------------------------------
-- Table `heroes_dragons`.`values`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroes_dragons`.`values` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `avatar` VARCHAR(45) NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroes_dragons`.`values_character_sheet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroes_dragons`.`values_character_sheet` (
  `values_id` INT NOT NULL,
  `character_sheet_id` INT NOT NULL,
  `character_sheet_characters_sheets_id` INT NOT NULL,
  PRIMARY KEY (`values_id`, `character_sheet_id`, `character_sheet_characters_sheets_id`),
  CONSTRAINT `fk_values_has_character_sheet_values1`
    FOREIGN KEY (`values_id`)
    REFERENCES `heroes_dragons`.`values` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_values_has_character_sheet_character_sheet1`
    FOREIGN KEY (`character_sheet_id` , `character_sheet_characters_sheets_id`)
    REFERENCES `heroes_dragons`.`character_sheet` (`id` , `characters_sheets_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_values_has_character_sheet_character_sheet1_idx` ON `heroes_dragons`.`values_character_sheet` (`character_sheet_id` ASC, `character_sheet_characters_sheets_id` ASC);

CREATE INDEX `fk_values_has_character_sheet_values1_idx` ON `heroes_dragons`.`values_character_sheet` (`values_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
