-- MySQL Script generated by MySQL Workbench
-- Sun May  3 12:19:03 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema heroes_dragons
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema heroes_dragons
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `heroes_dragons` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `heroes_dragons` ;

-- -----------------------------------------------------
-- Table `heroes_dragons`.`history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroes_dragons`.`history` (
  `idHistory` INT NOT NULL AUTO_INCREMENT,
  `charactersHistory` LONGTEXT NULL,
  `personalityTrait` VARCHAR(45) NULL,
  `ideal` VARCHAR(45) NULL,
  `link` VARCHAR(45) NULL,
  `default` VARCHAR(45) NULL,
  `masteryLanguage` VARCHAR(45) NULL,
  PRIMARY KEY (`idHistory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroes_dragons`.`classe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroes_dragons`.`classe` (
  `idClasse` INT NOT NULL AUTO_INCREMENT,
  `classeName` VARCHAR(45) NULL,
  PRIMARY KEY (`idClasse`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroes_dragons`.`archetype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroes_dragons`.`archetype` (
  `idArchetype` INT NOT NULL AUTO_INCREMENT,
  `archetypeName` VARCHAR(45) NULL,
  PRIMARY KEY (`idArchetype`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroes_dragons`.`alignement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroes_dragons`.`alignement` (
  `idAlignement` INT NOT NULL AUTO_INCREMENT,
  `alignementName` VARCHAR(45) NULL,
  PRIMARY KEY (`idAlignement`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroes_dragons`.`race`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroes_dragons`.`race` (
  `idRace` INT NOT NULL AUTO_INCREMENT,
  `raceName` VARCHAR(45) NULL,
  PRIMARY KEY (`idRace`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroes_dragons`.`skillsDexterity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroes_dragons`.`skillsDexterity` (
  `idSkillsDexterity` INT NOT NULL AUTO_INCREMENT,
  `dexterity` INT NULL,
  `diceSave` INT NULL,
  `throwSave` INT NULL,
  `modifier` INT NULL,
  `mastery` TINYINT(0) NULL,
  PRIMARY KEY (`idSkillsDexterity`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroes_dragons`.`skillsStrength`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroes_dragons`.`skillsStrength` (
  `idSkillsStrength` INT NOT NULL AUTO_INCREMENT,
  `strength` INT NULL,
  `diceSave` INT NULL,
  `throwSave` INT NULL,
  `modifier` INT NULL,
  `mastery` TINYINT(0) NULL,
  PRIMARY KEY (`idSkillsStrength`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroes_dragons`.`skillsCharisma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroes_dragons`.`skillsCharisma` (
  `idSkillsCharisma` INT NOT NULL AUTO_INCREMENT,
  `charisma` INT NULL,
  `diceSave` INT NULL,
  `throwSave` INT NULL,
  `modifier` INT NULL,
  `mastery` TINYINT(0) NULL,
  PRIMARY KEY (`idSkillsCharisma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroes_dragons`.`skillsWisdom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroes_dragons`.`skillsWisdom` (
  `idSkillsWisdom` INT NOT NULL AUTO_INCREMENT,
  `wisdom` INT NULL,
  `diceSave` INT NULL,
  `throwSave` INT NULL,
  `modifier` INT NULL,
  `mastery` TINYINT(0) NULL,
  PRIMARY KEY (`idSkillsWisdom`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroes_dragons`.`skillsSmart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroes_dragons`.`skillsSmart` (
  `idSkillsSmart` INT NOT NULL AUTO_INCREMENT,
  `smart` INT NULL,
  `diceSave` INT NULL,
  `throwSave` INT NULL,
  `modifier` INT NULL,
  `mastery` TINYINT(0) NULL,
  PRIMARY KEY (`idSkillsSmart`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroes_dragons`.`skillsConstitution`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroes_dragons`.`skillsConstitution` (
  `idSkillsConstitution` INT NOT NULL AUTO_INCREMENT,
  `constitution` INT NULL,
  `diceSave` INT NULL,
  `throwSave` INT NULL,
  `modifier` INT NULL,
  `mastery` TINYINT(0) NULL,
  PRIMARY KEY (`idSkillsConstitution`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroes_dragons`.`abilities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroes_dragons`.`abilities` (
  `idAbilities` INT NOT NULL AUTO_INCREMENT,
  `acrobatics` INT NULL,
  `arcane` INT NULL,
  `athletics` INT NULL,
  `discretion` INT NULL,
  `dressage` INT NULL,
  `retraction` INT NULL,
  `history` INT NULL,
  `investigation` INT NULL,
  `medicine` INT NULL,
  `nature` INT NULL,
  `perception` INT NULL,
  `perspicacity` INT NULL,
  `persuasion` INT NULL,
  `religion` INT NULL,
  `representation` INT NULL,
  `trickery` INT NULL,
  `survival` INT NULL,
  PRIMARY KEY (`idAbilities`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroes_dragons`.`skillsBonus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroes_dragons`.`skillsBonus` (
  `idSkillsBonus` INT NOT NULL AUTO_INCREMENT,
  `masteryBonus` INT NULL,
  `amourClasse` INT NULL,
  `initiative` INT NULL,
  `perception` INT NULL,
  `speed` INT NULL,
  PRIMARY KEY (`idSkillsBonus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroes_dragons`.`skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroes_dragons`.`skills` (
  `idSkills` INT(11) NOT NULL,
  `idSkillsDexterity` INT NOT NULL,
  `idSkillsStrength` INT NOT NULL,
  `idSkillsCharisma` INT NOT NULL,
  `idSkillsWisdom` INT NOT NULL,
  `idSkillsSmart` INT NOT NULL,
  `idSkillsConstitution` INT NOT NULL,
  `idAbilities` INT NOT NULL,
  `idSkillsBonus` INT NOT NULL,
  PRIMARY KEY (`idSkills`),
  CONSTRAINT `fk_skills_skillsDexterity1`
    FOREIGN KEY (`idSkillsDexterity`)
    REFERENCES `heroes_dragons`.`skillsDexterity` (`idSkillsDexterity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_skills_skillsStrength1`
    FOREIGN KEY (`idSkillsStrength`)
    REFERENCES `heroes_dragons`.`skillsStrength` (`idSkillsStrength`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_skills_skillsCharisma1`
    FOREIGN KEY (`idSkillsCharisma`)
    REFERENCES `heroes_dragons`.`skillsCharisma` (`idSkillsCharisma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_skills_skillsWisdom1`
    FOREIGN KEY (`idSkillsWisdom`)
    REFERENCES `heroes_dragons`.`skillsWisdom` (`idSkillsWisdom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_skills_skillsSmart1`
    FOREIGN KEY (`idSkillsSmart`)
    REFERENCES `heroes_dragons`.`skillsSmart` (`idSkillsSmart`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_skills_skillsConstitution1`
    FOREIGN KEY (`idSkillsConstitution`)
    REFERENCES `heroes_dragons`.`skillsConstitution` (`idSkillsConstitution`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_skills_abilities1`
    FOREIGN KEY (`idAbilities`)
    REFERENCES `heroes_dragons`.`abilities` (`idAbilities`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_skills_skillsBonus1`
    FOREIGN KEY (`idSkillsBonus`)
    REFERENCES `heroes_dragons`.`skillsBonus` (`idSkillsBonus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_skills_skillsDexterity1_idx` ON `heroes_dragons`.`skills` (`idSkillsDexterity` ASC) VISIBLE;

CREATE INDEX `fk_skills_skillsStrength1_idx` ON `heroes_dragons`.`skills` (`idSkillsStrength` ASC) VISIBLE;

CREATE INDEX `fk_skills_skillsCharisma1_idx` ON `heroes_dragons`.`skills` (`idSkillsCharisma` ASC) VISIBLE;

CREATE INDEX `fk_skills_skillsWisdom1_idx` ON `heroes_dragons`.`skills` (`idSkillsWisdom` ASC) VISIBLE;

CREATE INDEX `fk_skills_skillsSmart1_idx` ON `heroes_dragons`.`skills` (`idSkillsSmart` ASC) VISIBLE;

CREATE INDEX `fk_skills_skillsConstitution1_idx` ON `heroes_dragons`.`skills` (`idSkillsConstitution` ASC) VISIBLE;

CREATE INDEX `fk_skills_abilities1_idx` ON `heroes_dragons`.`skills` (`idAbilities` ASC) VISIBLE;

CREATE INDEX `fk_skills_skillsBonus1_idx` ON `heroes_dragons`.`skills` (`idSkillsBonus` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `heroes_dragons`.`spell`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroes_dragons`.`spell` (
  `idSpell` INT NOT NULL AUTO_INCREMENT,
  `spellName` VARCHAR(45) NULL,
  `attack` VARCHAR(45) NULL,
  `degat` VARCHAR(45) NULL,
  `degatType` VARCHAR(45) NULL,
  PRIMARY KEY (`idSpell`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroes_dragons`.`weapons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroes_dragons`.`weapons` (
  `idweapons` INT NOT NULL AUTO_INCREMENT,
  `weaponName` VARCHAR(45) NULL,
  `attack` VARCHAR(45) NULL,
  `degat` VARCHAR(45) NULL,
  `degatType` VARCHAR(45) NULL,
  PRIMARY KEY (`idweapons`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroes_dragons`.`attackSpell`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroes_dragons`.`attackSpell` (
  `idattackSpell` INT NOT NULL AUTO_INCREMENT,
  `idSpell` INT NOT NULL,
  `idweapons` INT NOT NULL,
  PRIMARY KEY (`idattackSpell`),
  CONSTRAINT `fk_attackSpell_spell1`
    FOREIGN KEY (`idSpell`)
    REFERENCES `heroes_dragons`.`spell` (`idSpell`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_attackSpell_weapons1`
    FOREIGN KEY (`idweapons`)
    REFERENCES `heroes_dragons`.`weapons` (`idweapons`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_attackSpell_spell1_idx` ON `heroes_dragons`.`attackSpell` (`idSpell` ASC) VISIBLE;

CREATE INDEX `fk_attackSpell_weapons1_idx` ON `heroes_dragons`.`attackSpell` (`idweapons` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `heroes_dragons`.`deathSave`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroes_dragons`.`deathSave` (
  `iddeathSave` INT NOT NULL AUTO_INCREMENT,
  `success1` TINYINT(0) NULL,
  `success2` TINYINT(0) NULL,
  `success3` TINYINT(0) NULL,
  `failure1` TINYINT(0) NULL,
  `failure2` TINYINT(0) NULL,
  `failure3` TINYINT(0) NULL,
  PRIMARY KEY (`iddeathSave`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroes_dragons`.`health`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroes_dragons`.`health` (
  `idHealth` INT NOT NULL AUTO_INCREMENT,
  `maxLifePoints` INT NULL,
  `lifeDice` VARCHAR(45) NULL,
  `actualLifePoints` INT NULL,
  `tiredLevel` INT NULL,
  `lifeDiceSpend` INT NULL,
  `idDeathSave` INT NULL,
  `iddeathSave` INT NOT NULL,
  PRIMARY KEY (`idHealth`),
  CONSTRAINT `fk_health_deathSave1`
    FOREIGN KEY (`iddeathSave`)
    REFERENCES `heroes_dragons`.`deathSave` (`iddeathSave`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_health_deathSave1_idx` ON `heroes_dragons`.`health` (`iddeathSave` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `heroes_dragons`.`gearsValues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroes_dragons`.`gearsValues` (
  `idGearsValues` INT NOT NULL AUTO_INCREMENT,
  `PP` INT NULL,
  `PO` INT NULL,
  `PE` INT NULL,
  `PA` INT NULL,
  `PC` INT NULL,
  PRIMARY KEY (`idGearsValues`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroes_dragons`.`gears`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroes_dragons`.`gears` (
  `idgears` INT NOT NULL AUTO_INCREMENT,
  `description` LONGTEXT NULL,
  `idGearsValues` INT NOT NULL,
  PRIMARY KEY (`idgears`),
  CONSTRAINT `fk_gears_gearsValues1`
    FOREIGN KEY (`idGearsValues`)
    REFERENCES `heroes_dragons`.`gearsValues` (`idGearsValues`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_gears_gearsValues1_idx` ON `heroes_dragons`.`gears` (`idGearsValues` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `heroes_dragons`.`sheetValues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroes_dragons`.`sheetValues` (
  `idSheetValues` INT(11) NOT NULL AUTO_INCREMENT,
  `updatedAt` DATETIME NULL DEFAULT NULL,
  `createdAt` DATETIME NULL DEFAULT NULL,
  `idClasse` INT NOT NULL,
  `idArchetype` INT NOT NULL,
  `idAlignement` INT NOT NULL,
  `idRace` INT NOT NULL,
  `idSkills` INT(11) NOT NULL,
  `idattackSpell` INT NOT NULL,
  `idHealth` INT NOT NULL,
  `idgears` INT NOT NULL,
  PRIMARY KEY (`idSheetValues`),
  CONSTRAINT `fk_sheetValues_classe1`
    FOREIGN KEY (`idClasse`)
    REFERENCES `heroes_dragons`.`classe` (`idClasse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sheetValues_archetype1`
    FOREIGN KEY (`idArchetype`)
    REFERENCES `heroes_dragons`.`archetype` (`idArchetype`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sheetValues_alignement1`
    FOREIGN KEY (`idAlignement`)
    REFERENCES `heroes_dragons`.`alignement` (`idAlignement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sheetValues_race1`
    FOREIGN KEY (`idRace`)
    REFERENCES `heroes_dragons`.`race` (`idRace`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sheetValues_skills1`
    FOREIGN KEY (`idSkills`)
    REFERENCES `heroes_dragons`.`skills` (`idSkills`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sheetValues_attackSpell1`
    FOREIGN KEY (`idattackSpell`)
    REFERENCES `heroes_dragons`.`attackSpell` (`idattackSpell`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sheetValues_health1`
    FOREIGN KEY (`idHealth`)
    REFERENCES `heroes_dragons`.`health` (`idHealth`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sheetValues_gears1`
    FOREIGN KEY (`idgears`)
    REFERENCES `heroes_dragons`.`gears` (`idgears`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Contenu des differents manuels d\'utilisation.';

CREATE INDEX `fk_sheetValues_classe1_idx` ON `heroes_dragons`.`sheetValues` (`idClasse` ASC) VISIBLE;

CREATE INDEX `fk_sheetValues_archetype1_idx` ON `heroes_dragons`.`sheetValues` (`idArchetype` ASC) VISIBLE;

CREATE INDEX `fk_sheetValues_alignement1_idx` ON `heroes_dragons`.`sheetValues` (`idAlignement` ASC) VISIBLE;

CREATE INDEX `fk_sheetValues_race1_idx` ON `heroes_dragons`.`sheetValues` (`idRace` ASC) VISIBLE;

CREATE INDEX `fk_sheetValues_skills1_idx` ON `heroes_dragons`.`sheetValues` (`idSkills` ASC) VISIBLE;

CREATE INDEX `fk_sheetValues_attackSpell1_idx` ON `heroes_dragons`.`sheetValues` (`idattackSpell` ASC) VISIBLE;

CREATE INDEX `fk_sheetValues_health1_idx` ON `heroes_dragons`.`sheetValues` (`idHealth` ASC) VISIBLE;

CREATE INDEX `fk_sheetValues_gears1_idx` ON `heroes_dragons`.`sheetValues` (`idgears` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `heroes_dragons`.`sheet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroes_dragons`.`sheet` (
  `idSheet` INT(11) NOT NULL AUTO_INCREMENT,
  `characterName` VARCHAR(45) NULL DEFAULT NULL,
  `description` LONGTEXT NULL,
  `experience` INT NULL,
  `level` INT NULL,
  `other` LONGTEXT NULL,
  `createdAt` DATETIME NULL DEFAULT NULL,
  `updatedAt` DATETIME NULL DEFAULT NULL,
  `abilitiesFeatures` LONGTEXT NULL,
  `idHistory` INT NOT NULL,
  `idSheetValues` INT(11) NOT NULL,
  PRIMARY KEY (`idSheet`),
  CONSTRAINT `fk_sheet_history1`
    FOREIGN KEY (`idHistory`)
    REFERENCES `heroes_dragons`.`history` (`idHistory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sheet_sheetValues1`
    FOREIGN KEY (`idSheetValues`)
    REFERENCES `heroes_dragons`.`sheetValues` (`idSheetValues`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_sheet_history1_idx` ON `heroes_dragons`.`sheet` (`idHistory` ASC) VISIBLE;

CREATE INDEX `fk_sheet_sheetValues1_idx` ON `heroes_dragons`.`sheet` (`idSheetValues` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `heroes_dragons`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroes_dragons`.`roles` (
  `idRoles` INT(11) NOT NULL AUTO_INCREMENT,
  `isAdminUser` TINYINT(4) NULL DEFAULT NULL,
  `createdAt` DATETIME NULL DEFAULT NULL,
  `updatedAt` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`idRoles`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `heroes_dragons`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroes_dragons`.`users` (
  `idUsers` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NULL DEFAULT NULL,
  `updatedAt` DATETIME NULL DEFAULT NULL,
  `idRoles` INT(11) NOT NULL,
  `idSheet` INT(11) NOT NULL,
  PRIMARY KEY (`idUsers`),
  CONSTRAINT `fk_users_roles`
    FOREIGN KEY (`idRoles`)
    REFERENCES `heroes_dragons`.`roles` (`idRoles`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_users_sheet1`
    FOREIGN KEY (`idSheet`)
    REFERENCES `heroes_dragons`.`sheet` (`idSheet`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_users_roles_idx` ON `heroes_dragons`.`users` (`idRoles` ASC) VISIBLE;

CREATE INDEX `fk_users_sheet1_idx` ON `heroes_dragons`.`users` (`idSheet` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
